on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
jobs:
  my_job:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.2.2
    - run: gcc C-Strike.c -o C-Strike
